export const genresJSON = {
    action: "Action",
    comedy: "Comedy",
    drama: "Drama",
    scifi: "Sci-Fi",
    thriller: "Thriller",
    fantasy: "Fantasy",
    horror: "Horror",
    romance: "Romance",
    documentary: "Documentary",
    adventure: "Adventure",
    animation: "Animation",
    crime: "Crime",
    family: "Family",
    mystery: "Mystery",
    war: "War",
    western: "Western",
    musical: "Musical",
    historical: "Historical",
    biography: "Biography",
    sports: "Sports",
}

export const genresArray = [
    "Action",
    "Comedy",
    "Drama",
    "Sci-Fi",
    "Thriller",
    "Fantasy",
    "Horror",
    "Romance",
    "Documentary",
    "Adventure",
    "Animation",
    "Crime",
    "Family",
    "Mystery",
    "War",
    "Western",
    "Musical",
    "Historical",
    "Biography",
    "Sports"
];