export const contentData = [
    {
        id: 1,
        title: 'Mirzapur',
        image: 'https://static.toiimg.com/photo/78801768.cms',
        description: 'A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Violence', 'Tragedy', 'Business', 'Politics']
    },
    {
        id: 2,
        title: 'Panchayat',
        image: 'https://www.koimoi.com/wp-content/new-galleries/2024/05/panchayat-season-3-review.jpg',
        description: 'Description of Panchayat',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 3,
        title: 'Stranger Things',
        image: 'https://wallpapers.com/images/featured/stranger-things-cast-pictures-8t1mu58lblncvhaw.jpg',
        description: 'Description of Popular Show 3',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 4,
        title: 'Money Heist',
        image: 'https://wallpapers.com/images/hd/professor-money-heist-digital-paint-1yegj3ptnd8g5noc.jpg',
        description: 'Description of Popular Show 4',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 5,
        title: 'Pekay Blinders',
        image: 'https://wallpapers.com/images/hd/peaky-blinders-1920-x-1080-picture-oionvgpdwqhab8k1.jpg',
        description: 'Description of Popular Show 5',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 6,
        title: 'Daredevils',
        image: 'https://wallpapers.com/images/featured/daredevil-358ifos2eg2ijm3t.jpg',
        description: 'Description of Popular Show 6',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 7,
        title: 'Fight For My Way',
        image: 'https://puui.wetvinfo.com/vcover_hz_pic/0/m5ag6gv6uug3vti1597147795657/0',
        description: 'Description of Popular Show 7',
        year: '2023',
        duration: '2h 8m',
        language: 'Korean',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 8,
        title: 'Asur',
        image: 'https://m.media-amazon.com/images/M/MV5BYjg2NDczMTAtYzk2YS00YTU2LTg4NTMtMDU0OGRhNDgwMmQyXkEyXkFqcGdeQXVyNDAzNDk0MTQ@._V1_.jpg',
        description: 'Description of Popular Show 8',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 9,
        title: 'Avatar',
        image: 'https://www.cnet.com/a/img/resize/bc48bbd2f4dbb7f5799eb4bc28bdcf6f19f6f408/hub/2022/05/10/708507de-bb07-4c16-9a94-bbf206a59fd5/avatar.jpg?auto=webp&fit=crop&height=675&width=1200',
        description: 'Description of Popular Show 9',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 10,
        title: 'Titanic',
        image: 'https://media.cnn.com/api/v1/images/stellar/prod/230213144330-02-titanic-25th-anniversary-restricted.jpg?c=original',
        description: 'Description of Popular Show 10',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 11,
        title: '3 Idiots',
        image: 'https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2023/06/3-idiot-1688114504.jpg',
        description: 'Description of Popular Show 11',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 12,
        title: 'Interstellar',
        image: 'https://wallpapers.com/images/featured/interstellar-d5hpgadclxszmpeh.jpg',
        description: 'Description of Popular Show 12',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 13,
        title: 'Jawan',
        image: 'https://i.ytimg.com/vi/d8zDiyuSctQ/maxresdefault.jpg',
        description: 'Description of Popular Show 13',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 14,
        title: 'Animal',
        image: 'https://media5.bollywoodhungama.in/wp-content/uploads/2019/09/Animal-13.jpg',
        description: 'Description of Popular Show 14',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 15,
        title: 'Hridayam',
        image: 'https://www.kerala9.com/wp-content/uploads/2022/01/hridayam-movie-stills-007-1024x785.jpg',
        description: 'Description of Popular Show 15',
        year: '2023',
        duration: '2h 8m',
        language: 'Malayalam',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 16,
        title: 'Chhichhore',
        image: 'https://img1.hotstarext.com/image/upload/f_auto/sources/r1/cms/prod/3343/1707280633343-i',
        description: 'Description of Popular Show 16',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 17,
        title: 'Kota Factory 3',
        image: 'https://static.toiimg.com/photo/msid-85893218.jpeg',
        description: 'Description of Popular Show 17',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 18,
        title: 'Heeramandi',
        image: 'https://assets.gqindia.com/photos/662f8c593a3c145ad3e9bab4/master/pass/Heeramandi-cast-fees.jpg',
        description: 'Description of Popular Show 18',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 19,
        title: 'Premalu',
        image: 'https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/1032/1712839861032-i',
        description: 'Description of Popular Show 19',
        year: '2023',
        duration: '2h 8m',
        language: 'Malayalam',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 20,
        title: 'Laapataa Ladies',
        image: 'https://assets-in.bmscdn.com/discovery-catalog/events/et00351955-wrdxrhzkyh-landscape.jpg',
        description: 'Description of Popular Show 20',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 21,
        title: 'Spiderman',
        image: 'https://wallpapers.com/images/featured/spiderman-p4ashmgeamn2mvkn.jpg',
        description: 'Description of Popular Show 21',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 22,
        title: 'Mr. and Mrs. Mahi',
        image: 'https://images.moneycontrol.com/static-mcnews/2024/05/20240508075442_IMG_8699.png?impolicy=website&width=1600&height=900',
        description: 'Description of Popular Show 22',
        year: '2023',
        duration: '2h 8m',
        language: 'Hindi',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 23,
        title: 'Tarot',
        image: 'https://www.tarotmovie.com/images/share.jpg',
        description: 'Description of Popular Show 23',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    {
        id: 24,
        title: 'The Fail Guy',
        image: 'https://i.ytimg.com/vi/EySdVK0NK1Y/maxresdefault.jpg',
        description: 'Description of Popular Show 24',
        year: '2023',
        duration: '2h 8m',
        language: 'English',
        rating: 'U/A 13+',
        tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 25, 
      title: 'Avengers: Endgame', 
      image: 'https://wallpapers.com/images/featured/avengers-endgame-mghdp4gaqzu4q4us.jpg',
      description: 'Description of Popular Show 25',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 26, 
      title: 'Taare Zameen Par', 
      image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBPi29Knz30_alJWpRwN2L_rDi99Sq-6SXz9SY4cQ_k5k3uQv6OhzzuDj5GsAhJMTeY7C_zF2v-hA1j7X-P5NtG_Q08wkVcsRFWGnfbsvKzJofGTcmvRrP8bN0jkSvlWcVhz6-ksyxPNX0/s1600/Taare+Zameen+Par+6.jpg',
      description: 'Description of Popular Show 26',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 27, 
      title: 'Top Gun: Maverick', 
      image: 'https://media.licdn.com/dms/image/D5612AQG98IdkyV-GGA/article-cover_image-shrink_720_1280/0/1655225008484?e=2147483647&v=beta&t=G1jCALfkWgQkpTOz7_SHQKZjLpJrin6BX9Qod2Ltsnk',
      description: 'Description of Popular Show 27',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 28,
      title: 'Iron Man 3', 
      image: 'https://images6.alphacoders.com/392/392098.jpg',
      description: 'Description of Popular Show 28',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 29, 
      title: 'Yeh Jawaani Hai Deewani', 
      image: 'https://images.cnbctv18.com/wp-content/uploads/2023/06/Yeh-Jawaani-Hai-Deewani-1019x573.jpg',
      description: 'Description of Popular Show 29',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 30, 
      title: 'Fast & Furious', 
      image: 'https://static1.colliderimages.com/wordpress/wp-content/uploads/2023/05/fast-and-furious-vin-diesel.jpg',
      description: 'Description of Popular Show 30',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 31, 
      title: 'Zindagi Na Milegi Dobara', 
      image: 'https://wallpapercave.com/wp/wp7115082.jpg',
      description: 'Description of Popular Show 31',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
    { id: 32, 
      title: '500 Days of Summer', 
      image: 'https://filmdaze.net/wp-content/uploads/2019/01/500-days-summer-1200-1200-675-675-crop-000000.jpg',
      description: 'Description of Popular Show 32',
      year: '2023',
      duration: '2h 8m',
      language: 'English',
      rating: 'U/A 13+',
      tags: ['Drama', 'Tragedy', 'Slice of Life', 'Emotional']
    },
];